default:
    trainer: sac
    batch_size: 128
    buffer_size: 50000
    buffer_init_steps: 0
    hidden_units: 128
    init_entcoef: 1.0
    learning_rate: 3.0e-4
    learning_rate_schedule: constant
    max_steps: 5.0e5
    memory_size: 256
    normalize: false
    num_update: 1
    train_interval: 1
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 10000
    tau: 0.005
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

PhaorisLearning_SAC:
    trainer: sac
    summary_freq: 5000
    time_horizon: 2048
    batch_size: 128
    buffer_size: 25600
    buffer_init_steps: 4096
    init_entcoef: 0.05
    learning_rate: 5.0e-4
    normalize: true
    train_interval: 5
    hidden_units: 256
    num_layers: 3
    max_steps: 3.0e6
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        gail:
            strength: 0.6
            demo_path: demos/PhaorisEasy3Demo.demo
            gamma: 0.9
            encoding_size: 128
            use_actions: true
    behavioral_cloning:
        strength: 0.6
        demo_path: demos/PhaorisEasy3Demo.demo
        steps: 300000
        batch_size: 256